# Generated by Django 5.1.3 on 2024-11-29 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fat_percentage',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(70.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=1.85, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=70, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(300.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='workout_frequency',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
