# Generated by Django 5.1.3 on 2024-12-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='heart_max',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='heart_rest',
        ),
    ]
