# Generated by Django 5.1.3 on 2024-12-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_profile_picture_type_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
